### GET all blogs
GET http://localhost:3003/api/blogs

### POST a new blog
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpdG9zc29tbyIsImlkIjoiNjIxMTdiNjQ0NzI3NGEzZDM1NWJkY2M1IiwiaWF0IjoxNjQ1MzE1MzkyfQ.ybdL7s5et_9tZUo6DceB_Czim7VIiafxuLUzBYbhCnM

{
  "title": "The killing joke",
  "author": "J and Bat",
  "url": "killingjoke.com"
}
### DELETE a blog by id
DELETE http://localhost:3003/api/blogs/6210f7078afdcccbbdece754

### PUT a blog change by id
PUT http://localhost:3003/api/blogs/6204c8b1d68e291a2923129f
Content-Type: application/json

{
  "title": "Mr. J i love u",
  "author": "Harley",
  "url": "hquin.com.ux"
}