### GET all blogs
GET http://localhost:3003/api/blogs

### POST a new blog
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhdHdvbWFuIiwiaWQiOiI2MjBiNzEzZmMyY2FkYThlMGZkMTljMzciLCJpYXQiOjE2NDUzMjAwODh9.RzG1ddJtqBFrVdvPun1fGFN3WIQRrDrMPAhv8ixsFJk

{
  "title": "The killing joke",
  "author": "J and Bat",
  "url": "killingjoke.com"
}
### DELETE a blog by id
DELETE http://localhost:3003/api/blogs/6211889b0b1ae858b72b4feb
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpdG9zc29tbyIsImlkIjoiNjIxMTdiNjQ0NzI3NGEzZDM1NWJkY2M1IiwiaWF0IjoxNjQ1MzE5OTgzfQ.xf0CrQLfxXSuj4HM7gJL2LVrxt3_TjMEnRPRWMJTHKY

### PUT a blog change by id
PUT http://localhost:3003/api/blogs/6204c8b1d68e291a2923129f
Content-Type: application/json

{
  "title": "Mr. J i love u",
  "author": "Harley",
  "url": "hquin.com.ux"
}